# -*- coding: utf-8 -*-
"""countdown_timer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b2mhieF4amfhLs_IAMQQJJUy7294h_EZ

# Geri Sayım Sayacı (Countdown Timer)

Saniye değerini girerek geri sayım sayacı oluştur

Create countdown timer by entering the seconds value.
"""

#import time module
import time

#countdown function (cd), and divmod-> t/60 and mod value.
def cd(t):
  while t:
    mins,secs = divmod(t,60)
    timer = '{:02d}:{:02d}'.format(mins,secs)
    print(timer,end="\r")
    time.sleep(1)
    t -= 1

  print("Time is over!") #when remained time is zero, time is over

#enter the input in seconds
t=input("Enter time in seconds: ")

#call the countdown function
cd(int(t))